name: Build and Publish

env:
  BUILD_TYPE: Release  # 定义构建类型

permissions:
  contents: write  # 全局权限声明

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

  publish:
    needs: [create_release]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            ext: ''
            os_tag: linux
            build_dir_suffix: ""
          - os: macos-latest
            ext: ''
            os_tag: macos
            build_dir_suffix: ""
          - os: windows-latest
            ext: .exe
            os_tag: windows
            build_dir_suffix: "/${{ env.BUILD_TYPE }}"  # 动态注入构建类型

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # 32位构建
      - name: Create build32 dir
        run: cmake -E make_directory ${{github.workspace}}/build32

      - name: Configure 32-bit
        working-directory: ${{github.workspace}}/build32
        run: cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DSO_64=OFF

      - name: Build 32-bit
        working-directory: ${{github.workspace}}/build32
        run: cmake --build . --config ${{ env.BUILD_TYPE }}

      # 64位构建
      - name: Create build64 dir
        run: cmake -E make_directory ${{github.workspace}}/build64

      - name: Configure 64-bit
        working-directory: ${{github.workspace}}/build64
        run: cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DSO_64=ON

      - name: Build 64-bit
        working-directory: ${{github.workspace}}/build64
        run: cmake --build . --config ${{ env.BUILD_TYPE }}

      # 上传到 Release
      - name: Upload 32-bit
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build32${{ matrix.build_dir_suffix }}/SoFixer32${{ matrix.ext }}
          asset_name: SoFixer-${{ matrix.os_tag }}-32${{ matrix.ext }}
          asset_content_type: application/octet-stream

      - name: Upload 64-bit
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build64${{ matrix.build_dir_suffix }}/SoFixer64${{ matrix.ext }}
          asset_name: SoFixer-${{ matrix.os_tag }}-64${{ matrix.ext }}
          asset_content_type: application/octet-stream
